# Generated by Django 4.2.5 on 2024-08-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone2',
            field=models.CharField(default=1, max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
