# Generated by Django 4.2.5 on 2024-08-27 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Изображение категории', null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Изображение работы', upload_to='works/')),
                ('title', models.CharField(help_text='Название работы', max_length=255)),
                ('location', models.CharField(help_text='Место изготовления', max_length=255)),
                ('date_of_creation', models.CharField(help_text='Дата изготовления (текстом)', max_length=255)),
                ('materials', models.TextField(help_text='Материалы (список, можно использовать пунктирный список)')),
                ('advantages', models.TextField(help_text='Преимущества (список, можно использовать пунктирный список)')),
                ('for_decoration', models.TextField(help_text='Для оформления (список, можно использовать пунктирный список)')),
                ('care_and_use', models.TextField(help_text='Уход и эксплуатация (большой текст)')),
                ('category', models.ForeignKey(help_text='Категория работы', on_delete=django.db.models.deletion.CASCADE, related_name='works', to='main.category')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ['title'],
            },
        ),
    ]
